#!/usr/bin/env bash
# Configure /etc/hosts so localhost -> 127.0.0.2 and facebook.com -> 8.8.8.8

sed -i 's/^[[:space:]]*127\.0\.0\.1[[:space:]]\+localhost[[:space:]]*$/127.0.0.2\tlocalhost/' /etc/hosts
sed -i '/[[:space:]]facebook\.com[[:space:]]*$/d' /etc/hosts
echo '8.8.8.8 facebook.com' >> /etc/hosts
